/**
 * AUTO-GENERATED by the OpenCutAgent server. Do not edit by hand: the server
 * rewrites this file whenever a job is created or removed. Each job folder
 * (`src/jobs/<id>/`) owns its `Scene.tsx`; this file only registers them.
 */
import type { JobEntry } from "./types";

export const jobs: JobEntry[] = [];
